site_name: HengZhao's Knowledge Base
site_url: https://enlzhao.github.io/Notebook
copyright: Copyright &copy; 2022 - 2024 <a href="https://github.com/enlzhao" target="_blank" rel="noopener">某兰</a>
site_author: EnlZhao
site_description: 知识库

# Pages
nav: 
  - Hello: 
    - Hello: index.md
    - 友链: link.md
    - My ZJU: ms.md
  - Course:
    - 前言: Course/abstract.md
    - 计算机系统Ⅱ:
      - 计算机系统Ⅱ: Course/System2/index.md
    - 计算机系统Ⅲ:
      - 计算机系统Ⅲ: Course/System3/index.md
    - 数据结构基础: 
      - 数据结构基础: Course/FDS/index.md
      - 算法分析和抽象数据类型: Course/FDS/Lec01.md
      - 线性结构: Course/FDS/Lec02.md
      - 树: Course/FDS/Lec03.md
      - 图: Course/FDS/Lec04.md
      - 排序: Course/FDS/Lec05.md
      - 哈希: Course/FDS/Lec06.md
    - 高级数据结构与算法分析:
      - 高级数据结构与算法分析: Course/ADS/index.md
      - 数据结构:
        - AVL & Splay: Course/ADS/Lec01.md
        - Red-Black & B+: Course/ADS/Lec02.md
        - Heap: Course/ADS/Lec03.md
      - 算法分析:
        - Backtracking: Course/ADS/Lec04.md
        - Divide and Conquer: Course/ADS/Lec05.md
        - Dynamic Programming: Course/ADS/Lec06.md
        - Greedy: Course/ADS/Lec07.md
        - NP - Completeness: Course/ADS/Lec08.md
    - 面向对象程序设计:
      - 面向对象程序设计: Course/OOP/index.md
      - Beginning: Course/OOP/Lec01.md
      - Step in Object-Oriented: Course/OOP/Lec02.md
      - Container: Course/OOP/Lec03.md
      - Object Interactive: Course/OOP/Lec04.md
      - Key Words: Course/OOP/Lec05.md
      - Inheritance & Polymorphism: Course/OOP/Lec06.md
      - Copt Ctor & Overloaded Operators: Course/OOP/Lec07.md
      - Templates: Course/OOP/Lec08.md
      - Exception Handling: Course/OOP/Lec09.md
      - Smart Pointers: Course/OOP/Lec10.md
      - Class Design: Course/OOP/Lec11.md
      - Streams & 继承构造函数: Course/OOP/Lec12.md
    # - 密码学:
    #   - 密码学: Course/Crypto/index.md
    #   - 数学基础: Course/Crypto/Lec01.md
    #   - 古典密码: Course/Crypto/Lec02.md
    - 计算机动画: 
      - 计算机动画: Course/Computer-Animation/index.md
      - 简介: Course/Computer-Animation/1-计算机动画简介.md
      - 动画基本原则: Course/Computer-Animation/2-动画基本原则.md
      - 考试大纲: Course/Computer-Animation/FinalExam.md
    # - 面向信息安全的信号处理:
    #   - 面向信息安全的信号处理: Course/Signal-Processing/index.md
    #   - 信号与系统基础: Course/Signal-Processing/1-信号与系统基础.md
    - 网络安全原理与实践:
      - 网络安全原理与实践: Course/netsec/index.md
      - DDoS: Course/netsec/ddos.md
      - Route Security: Course/netsec/routesec.md
      - Anonymous Communication: Course/netsec/anonymity.md
      - Web Security: Course/netsec/websec.md
      - Email Security: Course/netsec/mailsec.md
      - Traffic Analysis: Course/netsec/traffic.md
      - Attack Traceback: Course/netsec/traceback.md
      - Network Protection: Course/netsec/webprotect.md
    - 编译原理:
      - 编译原理: Course/cp/index.md
      - Introduction: Course/cp/intro.md
      - 词法分析: Course/cp/lexical.md
      - 语法分析(自顶向下): Course/cp/parsing1.md
      - 语法分析(自底向上): Course/cp/parsing2.md
      # - 抽象语法: Course/cp/abstractSyntax.md
      - 语义分析&活动记录: Course/cp/semantic.md
      - 中间代码生成: Course/cp/intermediateCode.md
      # - 基本块与轨迹: Course/cp/basicBlock.md
      # - 指令选择: Course/cp/instructionSel.md
      # - 活跃变量分析: Course/cp/LivenessAnalysis.md
      # - 寄存器分配: Course/cp/RegAlloc.md
      # - 垃圾回收: Course/cp/GarbageCollection.md
      # - 面向对象语言: Course/cp/OOLang.md
      # - 循环优化: Course/cp/LoopOptimization.md
  - AI: 
    - Triviality:  
        - Triviality: AI/Triviality/index.md
        - 凸优化: AI/Triviality/ConvexOpt.md
        - 对抗攻击:
          - 对抗攻击: AI/Triviality/AdversarialAttack/index.md
          - FGSM: AI/Triviality/AdversarialAttack/FGSM.md
          - BIM: AI/Triviality/AdversarialAttack/BIM.md
          - PGD: AI/Triviality/AdversarialAttack/PGD.md
        - 范数: AI/Triviality/Norm.md
        - PyTorch: 
          - PyTorch: AI/PyTorch/index.md
          - A 60 Min BLITZ: 
            - A 60 Min BLITZ: AI/PyTorch/BLITZ/index.md
            - Tensors: AI/PyTorch/BLITZ/lec01.md
            - Autograd: AI/PyTorch/BLITZ/lec02.md
            - Neural Networks: AI/PyTorch/BLITZ/lec03.md
            - Training a Classifier: AI/PyTorch/BLITZ/lec04.md
    - 人工智能算法:
        - 人工智能算法: AI/aialgorithm/index.md
        - 随机森林算法: AI/aialgorithm/randomForest.md
    - 优化算法: 
        - 优化算法: AI/OptimAlgorithm/index.md
    - 学习准则: 
        - 学习准则: AI/LearningCriterion/index.md
    - RelatedCourses:
      - 机器学习 (西瓜书):
        - 机器学习 (西瓜书): AI/Courses/wtbook/index.md
        - 绪论: AI/Courses/wtbook/chap1.md
      # - DeepLearning: 
      #   - DeepLearning: AI/Courses/DeepLearning/index.md
      #   - Intrucution to Deep Learning: AI/Courses/DeepLearning/introduction.md
      #   - Neural Networks and Deep Learning: 
      #     - Neural Networks and Deep Learning: AI/Courses/DeepLearning/course1/index.md
      #   - Improving Deep Neural Networks: 
      #     - Improving Deep Neural Networks: AI/Courses/DeepLearning/course2/index.md
      #   - Structuring Machine Learning Projects: 
      #     - Structuring Machine Learning Projects: AI/Courses/DeepLearning/course3/index.md
      #   - Convolutional Neural Networks: 
      #     - Convolutional Neural Networks: AI/Courses/DeepLearning/course4/index.md
      #   - Building Sequence Models: 
      #     - Building Sequence Models: AI/Courses/DeepLearning/course5/index.md
      - CS229: 
        - CS229: AI/Courses/CS229/index.md
      - 动手学习深度学习:
        - 动手学习深度学习: AI/Courses/LiMu/index.md
        - 深度学习基础:
          - 预备知识: AI/Courses/LiMu/01.md
          - 线性神经网络: AI/Courses/LiMu/02.md
          - 多层感知机: AI/Courses/LiMu/03.md
          - 深度学习计算: AI/Courses/LiMu/04.md
        - 卷积神经网络:
          - 卷积神经网络: AI/Courses/LiMu/05.md
          - 现代卷机神经网络: AI/Courses/LiMu/06.md
        - 循环神经网络:
          - 循环神经网络: AI/Courses/LiMu/07.md
          - 现代循环神经网络: AI/Courses/LiMu/08.md
        - 注意力机制: AI/Courses/LiMu/09.md
        - 优化算法: AI/Courses/LiMu/10.md
        - 高性能计算: AI/Courses/LiMu/11.md
        - 计算机视觉: AI/Courses/LiMu/12.md
        - 自然语言处理: 
          - "自然语言处理: 预训练": AI/Courses/LiMu/13.md
          - "自然语言处理: 应用": AI/Courses/LiMu/14.md
  - Research:
    - Papers: 
      - Papers: research/Papers/index.md
      - "🔗 xNIDS: Explainixwng DL-NIDS...": https://www.yuque.com/enl_z/ghyd0i/cnckf8nkgw8dhlgn
      - "🔗 a Semantics-Aware Routing Anomaly Detection System": https://www.yuque.com/enl_z/ghyd0i/ka1hegwra5ocx2kw
      - "🔗 FLASH: NIDS via Provenance Graph Representation Learning": https://www.yuque.com/enl_z/ghyd0i/glgld6yafrwkhsnc
      - "🔗 KAIROS: IDS using Whole-system Provenance": https://www.yuque.com/enl_z/ghyd0i/po5brv18r5s09t0n
      - "🔗 Network Detection of Interactive SSH Impostors": https://www.yuque.com/enl_z/ghyd0i/lxu81od6gik3hv3q
    - Projects:
      - LLM Quantization: research/LLM/llm_quantization_guide.md
  - Triviality: 
    - Pummping Lemma: Triviality/PumpingLemma.md
    - Programming Language:
      - Python:
        - Python: python/index.md
        - Triviality: python/trivial.md
  - Tools: 
    - GitHub: 
      - GitHub: Triviality/GitHub/index.md
      - Basics: Triviality/GitHub/docs.md
      - Git Related: Triviality/GitHub/Git.md
    - 文档撰写 Markdown: Triviality/markdown.md
    - Missing Semester: 
      - Missing Semester: Triviality/The Missing Semester/index.md
      - Vim: Triviality/The Missing Semester/Vim.md
    - CMake: 
      - CMake: Triviality/CMake/index.md
      - 准备&试编译: Triviality/CMake/Lec01.md
      - 初体验: Triviality/CMake/Lec02.md

theme:
  name: material
  logo: Icon/Avatar.png
  custom_dir: overrides
  icon: 
    logo: material/airplane # 页面icon
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
      code: fontawesome/solid/code
      important: fontawesome/solid/exclamation
      think: fontawesome/solid/brain
      advertisment: fontawesome/solid/rectangle-ad
      def: def
  font: 
    text: LXGW WenKai Screen #JetBrains Mono
    code: JetBrains Mono
  favicon: Icon/Avatar.png
  palette:
    - scheme: Kleinland
      toggle:
        icon: material/toggle-switch
        name: Switch to Light_Pink mode
    - scheme: DustyPeony
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark_Pink mode
    - scheme: slate
      primary: DustyPeony
      toggle:
        icon: material/toggle-switch
        name: Switch to Light_Blue mode
  # 导航栏
  features:
    - navigation.tracking # 在url中使用标题定位锚点
    - navigation.tabs # nav top 目录显示在标题栏
    # - navigation.tabs.sticky  # 滚动是隐藏顶部 nav，需要配合 navigation.tabs 使用
    #- navigation.sections  # nav节点缩进
    #- navigation.expand  # 每次刷新都展开子节点
    - navigation.indexes  # 跟navigation.instant不兼容
    #- toc.integrate  # 目录展开在字节点下
    - navigation.top # 一键回顶 top
    - search.suggest
    - search.highlight
    - content.code.annotate
    - header.autohide
    - toc.separate
    - toc.follow
    # - content.action.edit
    # - content.action.view
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest

  language: zh # 一些提示性的文字会变成中文

repo_url: https://github.com/enlzhao/Notebook # 右上角点击跳转的链接
repo_name: Knowledge Base # 右上角的名字
## [bottom-left corner]

# [Extensions]
plugins:
  - search:
      separator: '[\s\u200b\-]'
  - encryptcontent:
      title_prefix: '[LOCK]'
      summary: AES encryption supported by unverbuggt@github's plugin
      placeholder: Provide password and press ENTER
      decryption_failure_message: Invalid password
      encryption_info_message: Contact me(Enl_Z) via methods provided in the comments section for access to this page
  - mermaid2:
      javascript: https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs 
  - glightbox
  - statistics
  # - blog
  #- tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
  # - git-revision-date-localized: # 显示最后一次修改时间
  #     type: timeago
  #     enable_creation_date: true

markdown_extensions:
  - toc:  #锚点
      permalink: true
      toc_depth: 5
  #独立术语表
  - abbr
  - pymdownx.snippets
  #提示、警告栏
  - admonition
  - pymdownx.details  # 提示块可折叠
  - pymdownx.superfences:   # 代码嵌套在列表里
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  #按钮
  - attr_list
  #代码块
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite  # 行内代码高亮
  #内容标签栏
  - pymdownx.tabbed:
      alternate_style: true 
  #表格
  - tables
  #注脚
  - footnotes
  #格式化处理
  - pymdownx.keys
  - pymdownx.mark   # 文本高亮
  - pymdownx.tilde  # 删除线下标
  - pymdownx.caret  # 下划线上标
  - pymdownx.critic # 增加删除修改高亮注释，可修饰行内或段落
  #图标
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  #图片
  - md_in_html
  #列表
  - def_list
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true
  #其他
  - smarty
  - meta
  - sane_lists
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem  # 对加粗和斜体更好的检测
  - pymdownx.smartsymbols # 符号转换
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: EnlZhao
      repo: enlzhao.github.io/Notebook
  - toc:
      permalink:  👀 # ⚓︎ # 显示锚点
  - pymdownx.tasklist:
      custom_checkbox: true  
  - nl2br
  
extra_javascript:
  # - assets/javascripts/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  - assets/javascripts/announcement.js
  

extra_css:
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - assets/extra_css/counter.css
  - assets/extra_css/giscus.css
  - assets/extra_css/webcolor.css
  - assets/extra_css/tasklist.css
  - assets/extra_css/flink.css
  - assets/extra_css/admonition.css
  - assets/extra_css/announcement.css

extra: 
  vssue: EnlZhao
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/enlzhao
      name: GitHub 
    - icon: fontawesome/solid/paper-plane
      link: mailto:hengzhao2002@gmail.com
      name: Outlook 
    - icon: fontawesome/brands/qq
      link: tencent://AddContact/?fromId=45&fromSubId=1&subcmd=all&uin=1613715141&website=www.oicqzone.com
      name: QQ 
    - icon: fontawesome/regular/chess-king
      link: https://enlzhao.github.io/
      name: Blog
